# Generated by Django 2.2.4 on 2020-02-09 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200208_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SB', 'Vegetables'), ('TS', 'Spice'), ('SK', 'Fruits'), ('HS', 'Fish')], max_length=2),
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('job', models.CharField(max_length=100, verbose_name='Service Name')),
                ('o_date', models.CharField(max_length=100, verbose_name='Date of Order')),
                ('d_date', models.CharField(max_length=100, verbose_name='Estimated Completion Date')),
                ('fn', models.CharField(max_length=100, verbose_name='First name')),
                ('ln', models.CharField(max_length=100, verbose_name='Last name')),
                ('ads', models.CharField(max_length=100, verbose_name='Phone')),
                ('status', models.CharField(max_length=100, verbose_name='Current Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectViewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('ip_address', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Object Viewed',
                'verbose_name_plural': 'Objects Viewed',
                'ordering': ['-timestamp'],
            },
        ),
    ]
