# Generated by Django 2.2.4 on 2020-03-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200210_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SB', 'Flat'), ('TS', 'Property'), ('SK', 'Furniture'), ('HS', 'Apartment')], max_length=2),
        ),
    ]
